version: 2
jobs:
  build:
    working_directory: /qmk_firmware
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/qmk_firmware.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/qmk_firmware.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=nyushi/qmk_firmware -t nyushi/qmk_firmware .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/qmk_firmware.tar nyushi/qmk_firmware
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/qmk_firmware.tar
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: docker push nyushi/qmk_firmware
      - run:
          name: Build firmware
          command: docker run -it --rm -v`pwd`:/qmk nyushi/qmk_firmware make fortitude60_nyushi/rev1:default
